# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 794bb130f0d967ef476b66e5527a098fef3f9c01619b6e70a73235cfac1847d45c85ecd51eb3159d237127b2279ded8733ded8eb33dc7635b795912a0a8dfd10

test:
  secret_key_base: 85c662d76908ca482b2aec1f936b757b382319fba045fa390e3ffe1a864d5cb065450d5e331642a0f356dbc6a11bb16e9026528eed11dc4758b1aaec3a0f8424

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
